2018-01-20 11:31:30,671 - main.py:19 - INFO - main - <module> - 本次测试开始执行，以下是详细日志:
2018-01-20 11:31:30,681 - main.py:40 - ERROR - main - <module> - Traceback (most recent call last):
  File "main.py", line 24, in <module>
    suite.addTests(loader.loadTestsFromTestCase(Login))#把测试类登陆方法加载到suite里
NameError: name 'Login' is not defined

2018-01-20 11:31:30,691 - main.py:41 - ERROR - main - <module> - 测试异常终止
2018-01-20 11:33:02,444 - main.py:20 - INFO - main - <module> - 本次测试开始执行，以下是详细日志:
2018-01-20 11:33:03,455 - remote_connection.py:222 - INFO - remote_connection - __init__ - Could not get IP address for host: 192.168.2.35
2018-01-20 11:33:05,475 - remote_connection.py:222 - INFO - remote_connection - __init__ - Could not get IP address for host: 192.168.2.35
2018-01-20 11:33:07,485 - remote_connection.py:222 - INFO - remote_connection - __init__ - Could not get IP address for host: 192.168.2.35
2018-01-20 11:33:12,856 - login_logout.py:36 - INFO - login_logout - test_user_login_test - test_admin_login_test start....
2018-01-20 11:33:25,820 - login_logout.py:36 - INFO - login_logout - test_user_login_test - test_admin_login_test start....
2018-01-20 11:33:38,446 - login_logout.py:36 - INFO - login_logout - test_user_login_test - test_admin_login_test start....
2018-01-20 11:33:44,240 - login_logout.py:42 - INFO - login_logout - test_user_login_test - test data is : admin, 123456, 退出
2018-01-20 11:33:44,923 - login_logout.py:44 - INFO - login_logout - test_user_login_test - test_user_login_test end....
2018-01-20 11:33:48,050 - main.py:36 - INFO - main - <module> - 测试顺利结束！
2018-01-20 11:38:52,136 - main.py:20 - INFO - main - <module> - 本次测试开始执行，以下是详细日志:
2018-01-20 11:38:57,019 - login_logout.py:36 - INFO - login_logout - test_user_login_test - test_admin_login_test start....
2018-01-20 11:39:09,796 - login_logout.py:36 - INFO - login_logout - test_user_login_test - test_admin_login_test start....
2018-01-20 11:39:22,668 - login_logout.py:36 - INFO - login_logout - test_user_login_test - test_admin_login_test start....
2018-01-20 11:39:28,070 - login_logout.py:42 - INFO - login_logout - test_user_login_test - test data is : admin, 123456, 退出
2018-01-20 11:39:28,735 - login_logout.py:44 - INFO - login_logout - test_user_login_test - test_user_login_test end....
2018-01-20 11:39:31,898 - main.py:36 - INFO - main - <module> - 测试顺利结束！
2018-01-20 11:44:32,004 - main.py:20 - INFO - main - <module> - 本次测试开始执行，以下是详细日志:
2018-01-20 11:44:36,400 - login_logout.py:36 - INFO - login_logout - test_user_login_test - test_admin_login_test start....
2018-01-20 11:44:41,969 - login_logout.py:46 - INFO - login_logout - test_user_login_test - test data is : , 123456, 登录失败
2018-01-20 11:44:42,648 - login_logout.py:48 - INFO - login_logout - test_user_login_test - test_user_login_test end....
2018-01-20 11:44:50,126 - login_logout.py:36 - INFO - login_logout - test_user_login_test - test_admin_login_test start....
2018-01-20 11:44:58,326 - login_logout.py:46 - INFO - login_logout - test_user_login_test - test data is : invalid, 123456, 登录失败
2018-01-20 11:44:59,071 - login_logout.py:48 - INFO - login_logout - test_user_login_test - test_user_login_test end....
2018-01-20 11:45:06,373 - login_logout.py:36 - INFO - login_logout - test_user_login_test - test_admin_login_test start....
2018-01-20 11:45:10,992 - login_logout.py:46 - INFO - login_logout - test_user_login_test - test data is : admin, 123456, 退出
2018-01-20 11:45:11,694 - login_logout.py:48 - INFO - login_logout - test_user_login_test - test_user_login_test end....
2018-01-20 11:45:14,788 - main.py:36 - INFO - main - <module> - 测试顺利结束！
